### ISSUE TITLE
Road construction sites below sourcers in baserooms never get finished. Remove/finish them?

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#89]

**Comment by TooAngel** [comment]
Yes, true.

A role can set `buildRoad = true` which makes sure roads are build on the path. This is also true for the last position of a sources. After reaching the last pos and setting the constructionSite the sourcer sets `routing.reached = true` and will skip road building.

I think they don't need to build the road, because of no more moving. In my mind fixing this is a bit more tricky or ugly than just changing one line. Pain < Advantage = Didn't touch yet. Feel free, would be cool.

**Comment by Somotaw** [comment]
adding to TODO list :)

**Comment by mschultheiss83** [comment]
fixed in https://github.com/TooAngel/screeps/pull/315?

**Comment by TooAngel** [comment]
> fixed in #315?

That would have been sooo cool :-) I still see them sometimes

**Comment by mschultheiss83** [comment]
i did not found them in myRooms

**Comment by mschultheiss83** [comment]
i think this is fixed see https://github.com/TooAngel/screeps/pull/498/files#diff-8676a6e81b3f4dc29af2900b07a60958R248
carries will build them up if there is a road construction site in range (<4)

**Comment by TooAngel** [comment]
K, will close it
